apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
patches:
  - path: configmap.yaml
    target: { kind: ConfigMap, name: atelier-app-config }
  - path: service-patch.yaml
    target: { kind: Service, name: atelier-app }
